### ISSUE TITLE
Kind of bug: Mod_GUI doesn't disappear from mob app

### ISSUE THREAD

**Issue by Tommixoft** [mewlips/nx-remote-controller-mod#2] opened 2016-06-24 00:42 UTC
Hi, first of all - you app is AWESOME!!!!! did not aspect to see camera full screen on android app! Also those 2 scroll wheels-just awesome :DD 
Anyways, i pressed MOD button in app -it showed me MOD_GUI of course. the problem is -it stayed in app screen whole the time, but in camera mod_gui was no longer visible (i closed it by pressing menu button on camera).

PS why you using SWAP? is it necessary? i would like to avoid writings to flash.

**Comment by mewlips** [comment] 2016-06-24 13:27
Staying of mod_gui in screen of mobile app is caused by socket that sending the x-window capture image is closed by unknown reason.

Early in develement, my daemon is frequently died. I was thinking the problem maybe caused by lack of memory.
Now, the daemon uses very small memory, and maybe swap is not necessary. I will get rid of it.

Thank you.

**Comment by Tommixoft** [comment] 2016-06-24 14:34
No, thank you im just idiot who complains and you rock star :) Sad that your work, and NX mod work is done separate. NX camera have potential but people don't want to collaborate and create one product. 
Your mod super awesome for people who uses drones, and so on. You should tell about your mod in Dpreview samsung forum.

**Comment by mewlips** [comment] 2016-07-01 16:28
bug fixed in v0.7

**Closed as completed by mewlips** 2016-07-01 16:28 UTC
